### ISSUE TITLE
Visualization framework research

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/peek-data#1]
- Voila
- Panel
- Holoviz
- Streamlit
- Grafana Labs

**Comment by SimonHeybrock** [comment]
I was looking for a talk about similar libraries that we once watch but could not find it. However, here is a different talk about the same libraries (and additional options for your list): https://www.youtube.com/watch?v=mZOIeOeswB0. I did not watch it, so I don't know if it is good.

**Comment by SimonHeybrock** [comment]
It might have been this one: https://www.youtube.com/watch?v=1UVghBXt6dY

**Comment by YooSunYoung** [comment]
For Grafana, I think it’s more suitable if you have to constantly monitor the stream and the output of the analysis is used in other interfaces. Will that be a case?

**Comment by SimonHeybrock** [comment]
> For Grafana, I think it’s more suitable if you have to constantly monitor the stream and the output of the analysis is used in other interfaces. Will that be a case?

There are some ideas (or long-term requirements) about "restreaming" the reduced data to data-analysis software. But people wanted to use Kafka for this as well.

**Comment by YooSunYoung** [comment]
These options below were reviewed because of this common benefits
- Separate backend not needed
- Well-documented
- Open sources (or we have access to)
- Python developer friendly
- Templates or pre-built solution provided (front-end knowledge not needed)


## Dash 
![Image](https://user-images.githubusercontent.com/17974113/219020432-c09ab02e-b167-4f0d-a177-9a2a796c0caa.png)
### Pros
- Very flexible
- A lot of examples that we might be able to use
- Similarity to flask and easy to have a complicated backend via flask. 
### Cons
- It might take a while to build a user-friendly, good-looking design.

## Streamlit
![Image](https://user-images.githubusercontent.com/17974113/219021353-b655c663-b255-4a11-9693-e2468e70a4bf.png)
### Pros
- Neat and user-friendly design already applied.
- Cacheing and resource handling provided seamlessly. 
- Easy to implement standalone web application, few lines of code needed. 
- Flexible, almost as much as dash.
- Well-documented and with help of helpful community.
### Cons
- We need to be careful not to put too much functions in the dashboard.
- Easy to have a various versions of software, which will cause more maintaining cost.

## Panel
![Image](https://user-images.githubusercontent.com/17974113/219021212-d8a3b122-27fd-4de2-9e30-b68a4449e626.png)
### Pros
- Neat look with various prebuilt solutions
- Easy and intuitive way of implementation
- Well documented. 
- Many plotting methods which also create user-interfaces provided. 
### Cons
- You might have to manually setup the design and layout if you're not using the supported plotting libraries.
### Comments
- It will be nice if we want to use their plotting libraries a lot.

## Voila
![Image](https://user-images.githubusercontent.com/17974113/219021403-5f300242-2ad2-44a7-8ecd-0e279dabe55b.png)
### Pros
- Directly translate Jupyter notebook into a web application.
### Cons
- Not easy to customise the pages.
- You might end up writing a separate backend.
### Comments
- If we give up possibility to extend this dashboard and aesthetic values or more user-friendly design, it'll be the easiest.

## Grafana Labs Dashboards
![Image](https://user-images.githubusercontent.com/17974113/219033106-8ade1d21-a54b-4712-a0da-de3c83d69ef2.png)
### Pros
- A lot of prebuilt solutions.
- Easy to connect to other Grafana services or distributed systems. 
### Cons
- Might need to maintain the access permit to the data or dashboard per users. 
- Not easy to customise minor things.
### Comments
- Seems like a good solution to monitor the data collection itself but not flexible enough for plotting the collected data.


## Other Options

| Shiny, flask, Jupyter, ipywidgets, qt, react, typescript, …

**Comment by YooSunYoung** [comment]
# References

- Python Dashboarding Shootout and Showdown (Coding Tech Workshop)
  https://www.youtube.com/watch?v=1UVghBXt6dY

- Data Revenue Blog Post
  https://www.datarevenue.com/en-blog/data-dashboarding-streamlit-vs-dash-vs-shiny-vs-voila

**Comment by YooSunYoung** [comment]
# Conclusion
No concrete decision is made for now.
- `streamlit`, `dash` and `panel` are all quite similar.
- We are not sure how we are going to render interactive plots at the moment and that might affect the decision.
- We might have more specific use-cases and requirements that will affect the decision.

Therefore we will just keep the visualization module simple enough to switch to another framework if needed.
