### ISSUE TITLE
Permanent name of the project

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/peek-data#12]
We need to decide which name to use for this project.

Here are the suggestions from the team:
- `visens` (VISualization for Ess Neutron Science: means 'seeing' in latin)
- `live`
- `seelive`
- `liveview`

Here are some suggestions from the `ChatGPT` based on the project description.
- [ ] StreamViz
- [ ] StreamDash
- [ ] StreamSci
- [ ] SciStream
- [ ] ExperiStream
- [ ] NeutronStream
- [ ] SciViz
- [ ] NeutronViz
- [ ] LabDash
- [ ] SciDash
- [ ] NeutronDash

Feel free to check the box to strike the names you don't want or unavailable.

**Comment by SimonHeybrock** [comment]
Dashboard? LiveData?

**Comment by YooSunYoung** [comment]
I think it shouldn’t have too generic name. It will be confusing and they are already taken in pypi.

**Comment by nvaytet** [comment]
@SimonHeybrock i thought we decided we would call our next package `beamlime` ;-)

**Comment by SimonHeybrock** [comment]
That would be an option if @YooSunYoung likes it (and we don't intend to rename `ess`->`beamlime`?)?

**Comment by SimonHeybrock** [comment]
But speaking of limes... how about `limelight`?

> The origins of “in the limelight,” which refers to **being the focus of public attention**, are linked to a type of stage lighting that was popular in the 19th century. The “lime” in limelight has nothing to do with the green citrus fruit but rather with a chemical compound, calcium oxide, also known as quicklime.

**Comment by nvaytet** [comment]
lime in beamlime could be Live Interactive Monitoring at Ess ;-)

**Comment by nvaytet** [comment]
limelight is also good, but apparently taken in pypi

**Comment by SimonHeybrock** [comment]
We can always prefix things with `scipp` or `ess`.

**Comment by YooSunYoung** [comment]
`beamlime` is a bit confusing but it’s for some reason, easy to remember.
Can `lime` be Live Interactive Monitoring Express? : D
Cause we’re gonna use the raw data from the kafka directly.

**Comment by YooSunYoung** [comment]
![image](https://user-images.githubusercontent.com/17974113/225243696-fef2ef6d-e1d3-41c3-841c-ccf479c89705.png)

**Comment by SimonHeybrock** [comment]
:+1: (maybe add one extra radial line in the lime, I think they usually have more?
