### ISSUE TITLE
Scipp repository template

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/peek-data#8]
Based on the result below, we can maybe create a repository template and use if for this repository....?

# Repository structure comparison

## depth=1
![image](https://user-images.githubusercontent.com/17974113/222152855-c2540cc3-b1b2-44c6-9532-786fbdc69bb6.png)

## depth=2
![image](https://user-images.githubusercontent.com/17974113/222154728-a0db426e-eba8-4f4e-9f15-83195674f53f.png)

**Comment by jl-wynen** [comment]
Is it possible to update a repo from a template?

Asking because making a new repo is rare and it is fine if that takes some manual work. But we often need to update several repos when we touch some build system/CI/etc setup.

**Comment by YooSunYoung** [comment]
I guess we can use `git submodule` but it doesn't really reduce the work.

So the typical scenario using `git submodule` will be

- Setup submodules in target repositories
- Update the repository of the submodule
- Update other repositories one by one with `git submodule update --remote`
- git add & git commit & git push & merge request &...

But, maybe we can hook this work in the CI workflow somehow, 

For example, to check if any submodules are updated and if yes, automatically create a branch, update the submodule and open a pull request...?

**Comment by jl-wynen** [comment]
A submodule would require all files to be in one place. So it would not work for pyproject, tox.ini, etc. Plus versioning with submodules is messy.

**Comment by YooSunYoung** [comment]
> A submodule would require all files to be in one place. So it would not work for pyproject, tox.ini, etc. Plus versioning with submodules is messy.

True... I will do it manually for now and think about this later if needed
